[package]
name = "fabric-types"
version = "0.1.0"
edition = "2021"

[dependencies]

bcs.workspace = true
move-core-types.workspace = true
serde.workspace = true
# fastcrypto.workspace = true

anyhow = "1.0.75"
serde_bytes = "0.11.12"
fastcrypto = "0.1.6"

